name: Docs
on:
  push:
    branches:
      - ci-workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12.0'
    - name: Install and Build
      run: |
        npm install
        npm run docs:build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with: 
        ACCESS_TOKEN: ${{ secrets.VITEPRESS }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run npm run docs:build
